main: me.eeshe.treasurehunt.TreasureHunt
name: TreasureHunt
version: ${project.version}
author: Eeshe
depend: [ PenPenLib ]
api-version: 1.13
folia-supported: true

commands:
  treasurehunt:
    aliases:
      - th